### ISSUE TITLE
The New Version Works, but ...

### ISSUE THREAD

**Issue by antonellomangone** [hieblmedia/simple-php-encrypter-decrypter#2]
The New Version Works, but it doesn't give back the same encoded strings as in the previous version, so I'll have to modify the old passwords ?

**Comment by hieblmedia** [comment]
Hello,
yes because, since PHP 5.6 the mcrypt behavior has changed. In the encrypter the key was hashed with sha1 (length is 20). But mcrypt allow only a length of 16, 24, etc. since PHP 5.6. There is no way to make a fallback for this situation.

The only thing you can do is:
1. Decrypt all password with the old version and PHP 5.5
2. Update to the new Version and make new encrypted passwords.

**Comment by antonellomangone** [comment]
Thanks a lot for the exaplanation, I though I was doing something wrong.

2016-04-04 13:17 GMT+02:00 Reinhard Hiebl notifications@github.com:
